#!/usr/bin/env python3
"""
Single-Subject EEG Window Noise & Sleep Stage Correlation Analyzer.

Inputs: A single metadata JSON file generated by the EEG window slicing pipeline.
Outputs:
1. Overall Window Rejection Summary
2. Sleep Stage Contingency Table & Rejection Rates
3. Statistical Correlation Test (Chi-Square Test of Independence & Cramér's V)
4. Hourly Temporal Noise Distribution Across Recording Timeline
5. Chronological Event Log of Rejected/Noisy Windows
"""

import argparse
import json
import sys
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency


def load_and_parse_metadata(json_path: Path) -> pd.DataFrame:
    """Loads metadata JSON and constructs a structured Pandas DataFrame."""
    with open(json_path, 'r') as f:
        data = json.load(f)

    subject_id = data.get("subject_id", json_path.stem)
    slices = data.get("slices", [])
    stages = data.get("stages", [])

    if len(slices) == 0:
        raise ValueError(f"No slice metadata found in {json_path}")

    records = []
    for idx, s in enumerate(slices):
        stage = stages[idx] if idx < len(stages) else "UNKNOWN"
        
        # Determine noise classification
        is_valid = s.get("is_valid", True)
        quality_status = s.get("quality_status", "OK")
        
        start_sec = s.get("start_sec", idx * 30.0)
        end_sec = s.get("end_sec", (idx + 1) * 30.0)
        
        records.append({
            "window_idx": s.get("window_idx", idx),
            "start_sec": start_sec,
            "end_sec": end_sec,
            "start_min": start_sec / 60.0,
            "start_hour": start_sec / 3600.0,
            "is_valid": is_valid,
            "is_noisy": not is_valid,
            "quality_status": quality_status,
            "stage": stage.upper()
        })

    df = pd.DataFrame(records)
    df["subject_id"] = subject_id
    return df


def analyze_sleep_stage_correlation(df: pd.DataFrame):
    """Computes contingency tables, rejection percentages, and Chi-Square test."""
    print("\n" + "=" * 60)
    print(" 1. SLEEP STAGE VS. WINDOW NOISE CONTINGENCY ANALYSIS")
    print("=" * 60)

    # Contingency Table: Stage vs Window Status
    contingency = pd.crosstab(
        df['stage'], 
        df['is_valid'].map({True: 'Valid', False: 'Noisy/Rejected'}),
        margins=True,
        margins_name='Total'
    )

    # Rejection rate percentage per stage
    stage_summary = df.groupby('stage').agg(
        Total_Windows=('is_valid', 'count'),
        Valid_Windows=('is_valid', lambda x: x.sum()),
        Noisy_Windows=('is_noisy', lambda x: x.sum()),
        Rejection_Rate_Pct=('is_noisy', lambda x: (x.sum() / len(x)) * 100.0)
    ).reset_index()

    print("\n[Table 1: Window Counts and Rejection Rate by Sleep Stage]")
    print(stage_summary.to_string(index=False, float_format=lambda x: f"{x:.2f}%" if isinstance(x, float) else f"{x}"))

    # Statistical Test: Chi-Square Test of Independence
    # Exclude 'Total' row/column for test
    ct_test = pd.crosstab(df['stage'], df['is_noisy'])
    
    # Filter out stages with 0 occurrences to satisfy chi2 assumptions
    ct_test = ct_test.loc[(ct_test.sum(axis=1) > 0)]

    if ct_test.shape[0] > 1 and ct_test.shape[1] > 1 and ct_test.values.sum() > 0:
        chi2, p_val, dof, expected = chi2_contingency(ct_test)
        
        # Cramér's V effect size calculation
        n = ct_test.values.sum()
        min_dim = min(ct_test.shape) - 1
        cramers_v = np.sqrt(chi2 / (n * min_dim)) if min_dim > 0 else 0.0

        print("\n" + "-" * 60)
        print(" STATISTICAL CORRELATION TEST RESULTS")
        print("-" * 60)
        print(f" • Chi-Square Statistic (χ²): {chi2:.4f}")
        print(f" • Degrees of Freedom (dof): {dof}")
        print(f" • p-value:                  {p_val:.4e}")
        print(f" • Cramér's V (Effect Size): {cramers_v:.4f}")

        if p_val < 0.05:
            print("\n  Result: STATISTICALLY SIGNIFICANT (p < 0.05)")
            print("  Interpretation: Noisy window rejections are NOT randomly distributed across")
            print("  sleep stages. Specific sleep stages exhibit disproportionate artifact rates.")
        else:
            print("\n  Result: NOT STATISTICALLY SIGNIFICANT (p >= 0.05)")
            print("  Interpretation: Insufficient evidence to suggest noise occurrence depends on sleep stage.")
    else:
        print("\n[WARN] Insufficient variance across sleep stages to run Chi-Square test.")


def analyze_temporal_distribution(df: pd.DataFrame, bin_hours: float = 1.0):
    """Bins recording into hourly intervals to evaluate time-of-night noise progression."""
    print("\n" + "=" * 60)
    print(f" 2. TEMPORAL NOISE DISTRIBUTION ({bin_hours}-HOUR TIMELINE BINS)")
    print("=" * 60)

    max_hour = np.ceil(df['start_hour'].max())
    bins = np.arange(0, max_hour + bin_hours, bin_hours)
    labels = [f"Hour {int(b)}-{int(b+bin_hours)}" for b in bins[:-1]]

    df['time_bin'] = pd.cut(df['start_hour'], bins=bins, labels=labels, right=False)

    temporal_summary = df.groupby('time_bin', observed=False).agg(
        Total_Windows=('is_valid', 'count'),
        Noisy_Windows=('is_noisy', lambda x: x.sum()),
        Rejection_Rate_Pct=('is_noisy', lambda x: (x.sum() / len(x) * 100.0) if len(x) > 0 else 0.0),
        Dominant_Stage=('stage', lambda x: x.mode()[0] if not x.empty else 'N/A')
    ).reset_index()

    print("\n[Table 2: Hourly Rejection Profile Across Recording Duration]")
    print(temporal_summary.to_string(index=False, float_format=lambda x: f"{x:.2f}%" if isinstance(x, float) else f"{x}"))


def log_noisy_events(df: pd.DataFrame):
    """Displays a chronological event sequence of rejected windows."""
    noisy_df = df[df['is_noisy']].sort_values('start_sec')

    print("\n" + "=" * 60)
    print(f" 3. CHRONOLOGICAL LOG OF NOISY WINDOW EVENTS (Total: {len(noisy_df)})")
    print("=" * 60)

    if len(noisy_df) == 0:
        print("  All windows passed quality screening (0 noisy windows).")
        return

    print(f"{'Win ID':<8} {'Start Time':<12} {'End Time':<12} {'Stage':<8} {'Reason/Status':<25}")
    print("-" * 68)
    for _, row in noisy_df.iterrows():
        start_fmt = f"{int(row['start_min'] // 60):02d}h {int(row['start_min'] % 60):02d}m {int(row['start_sec'] % 60):02d}s"
        end_fmt = f"{int(row['end_sec'] // 3600):02d}h {int((row['end_sec'] % 3600) // 60):02d}m {int(row['end_sec'] % 60):02d}s"
        print(
            f"#{row['window_idx']:<7} {start_fmt:<12} {end_fmt:<12} {row['stage']:<8} {row['quality_status']:<25}"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Analyze noisy window occurrence, timeline distribution, and sleep stage correlation from metadata JSON."
    )
    parser.add_argument("--meta_json", type=str, required=True, help="Path to single subject metadata JSON file")
    args = parser.parse_args()

    json_path = Path(args.meta_json).resolve()
    if not json_path.exists():
        print(f"Error: Metadata file not found at '{json_path}'", file=sys.stderr)
        sys.exit(1)

    df = load_and_parse_metadata(json_path)

    subject_id = df['subject_id'].iloc[0]
    total_wins = len(df)
    noisy_wins = df['is_noisy'].sum()
    valid_wins = df['is_valid'].sum()
    rec_duration_hrs = (df['end_sec'].max() - df['start_sec'].min()) / 3600.0

    print("=" * 60)
    print(f" EEG WINDOW NOISE & SLEEP STAGE ANALYSIS REPORT")
    print(f" Subject ID:         {subject_id}")
    print(f" Recording File:     {json_path.name}")
    print(f" Total Duration:     {rec_duration_hrs:.2f} hours ({total_wins} windows)")
    print(f" Valid Windows:      {valid_wins} ({(valid_wins/total_wins)*100:.1f}%)")
    print(f" Noisy/Rejected:     {noisy_wins} ({(noisy_wins/total_wins)*100:.1f}%)")
    print("=" * 60)

    # 1. Sleep Stage Correlation & Contingency Analysis
    analyze_sleep_stage_correlation(df)

    # 2. Timeline / Temporal Breakdown
    analyze_temporal_distribution(df)

    # 3. Detailed Chronological Event Log
    log_noisy_events(df)


if __name__ == "__main__":
    main()