import argparse
import os
import time
from pathlib import Path
from typing import List, Tuple
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import classification_report, f1_score, accuracy_score
from tqdm import tqdm

# Import model architecture setup from our benchmark module
from 07b_real_world_benchmark import CBraModRealWorldBenchmark


class RealSleepEEGDataset(Dataset):
    """
    PyTorch Dataset that loads real preprocessed sleep EEG tensors (.npy) 
    using manifest CSVs generated by 03_label_dataset.py.
    """
    def __init__(self, manifest_csv: Path, memory_map: bool = True):
        self.manifest_csv = Path(manifest_csv)
        if not self.manifest_csv.exists():
            raise FileNotFoundError(f"Manifest file not found: {self.manifest_csv}")
            
        self.df = pd.read_csv(self.manifest_csv)
        self.memory_map = memory_map
        
        # Build index map mapping global dataset index -> (file_path, window_index inside file, label)
        self.samples: List[Tuple[Path, int, int]] = []
        self._index_dataset()

    def _index_dataset(self):
        print(f"Indexing samples from manifest: {self.manifest_csv.name}...")
        for _, row in self.df.iterrows():
            npy_path = Path(row["npy_path"])
            num_slices = int(row["num_slices"])
            label = int(row["label"])
            
            if not npy_path.exists():
                print(f"  [Warning] Missing tensor file: {npy_path}, skipping...")
                continue
                
            for idx in range(num_slices):
                self.samples.append((npy_path, idx, label))
                
        print(f"  -> Total index entries loaded: {len(self.samples)} windows across {len(self.df)} subjects.")

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        npy_path, window_idx, label = self.samples[idx]
        
        # Load single slice from disk (uses memory-mapping if enabled for low RAM utilization)
        if self.memory_map:
            data = np.load(npy_path, mmap_mode="r")
            slice_data = np.array(data[window_idx], dtype=np.float32)
        else:
            data = np.load(npy_path)
            slice_data = data[window_idx].astype(np.float32)

        x_tensor = torch.from_numpy(slice_data) # Shape: [Channels, Time_Samples] e.g., [64, 6000]
        y_tensor = torch.tensor(label, dtype=torch.long)
        
        return x_tensor, y_tensor


class EarlyStopping:
    """Early stopping handler to prevent overfitting on subject cohorts."""
    def __init__(self, patience: int = 5, min_delta: float = 1e-4):
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_score = None
        self.early_stop = False

    def __call__(self, val_f1: float) -> bool:
        if self.best_score is None:
            self.best_score = val_f1
        elif val_f1 < self.best_score + self.min_delta:
            self.counter += 1
            print(f"  [EarlyStopping] No improvement in Val F1 for {self.counter}/{self.patience} epochs.")
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = val_f1
            self.counter = 0
        return self.early_stop


def run_fine_tuning_pipeline(
    train_manifest: Path,
    val_manifest: Path,
    num_channels: int = 64,
    num_classes: int = 2,
    batch_size: int = 16,
    epochs: int = 20,
    lr_backbone: float = 1e-5,
    lr_head: float = 1e-3,
    weight_decay: float = 1e-4,
    num_workers: int = 4,
    checkpoint_dir: Path = Path("./checkpoints"),
    device_str: str = "cuda"
):
    """Executes multi-epoch fine-tuning using real dataset manifest inputs."""
    device = torch.device(device_str if torch.cuda.is_available() else "cpu")
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_model_path = checkpoint_dir / "cbramod_best_finetuned.pt"

    print(f"\n=== Initializing CBraMod Real-Data Fine-Tuning on [{device}] ===")

    # 1. Instantiate Datasets & DataLoaders from Manifests
    train_ds = RealSleepEEGDataset(train_manifest)
    val_ds = RealSleepEEGDataset(val_manifest)

    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True
    )

    # 2. Instantiate CBraMod Architecture
    model = CBraModRealWorldBenchmark(num_channels=num_channels, num_classes=num_classes).to(device)

    # 3. Configure Differential Learning Rates
    # Lower LR for pre-trained backbone; higher LR for classification head
    backbone_params = []
    head_params = []

    for name, param in model.named_parameters():
        if "classifier" in name or "head" in name:
            head_params.append(param)
        else:
            backbone_params.append(param)

    optimizer = torch.optim.AdamW([
        {"params": backbone_params, "lr": lr_backbone},
        {"params": head_params, "lr": lr_head}
    ], weight_decay=weight_decay)

    criterion = nn.CrossEntropyLoss()
    early_stopper = EarlyStopping(patience=5)

    best_val_f1 = 0.0

    print(f"Backbone LR: {lr_backbone} | Head LR: {lr_head} | Epochs: {epochs} | Batch Size: {batch_size}")
    print("=" * 70)

    # 4. Training & Validation Loop
    for epoch in range(1, epochs + 1):
        start_time = time.time()
        
        # --- TRAINING PHASE ---
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch:02d}/{epochs:02d} [Train]", leave=False)
        for x_batch, y_batch in pbar:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)

            optimizer.zero_grad()
            logits = model(x_batch)
            loss = criterion(logits, y_batch)
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * x_batch.size(0)
            preds = torch.argmax(logits, dim=1)
            train_correct += (preds == y_batch).sum().item()
            train_total += y_batch.size(0)

            pbar.set_postfix({"Loss": f"{loss.item():.4f}"})

        epoch_train_loss = train_loss / train_total
        epoch_train_acc = (train_correct / train_total) * 100.0

        # --- VALIDATION PHASE ---
        model.eval()
        val_loss = 0.0
        val_preds = []
        val_targets = []

        with torch.no_grad():
            for x_batch, y_batch in val_loader:
                x_batch, y_batch = x_batch.to(device), y_batch.to(device)
                logits = model(x_batch)
                loss = criterion(logits, y_batch)

                val_loss += loss.item() * x_batch.size(0)
                preds = torch.argmax(logits, dim=1)

                val_preds.extend(preds.cpu().numpy())
                val_targets.extend(y_batch.cpu().numpy())

        epoch_val_loss = val_loss / len(val_targets)
        epoch_val_acc = accuracy_score(val_targets, val_preds) * 100.0
        epoch_val_f1 = f1_score(val_targets, val_preds, average="macro")
        elapsed = time.time() - start_time

        print(
            f"Epoch [{epoch:02d}/{epochs:02d}] ({elapsed:.1f}s) | "
            f"Train Loss: {epoch_train_loss:.4f}, Acc: {epoch_train_acc:.2f}% | "
            f"Val Loss: {epoch_val_loss:.4f}, Acc: {epoch_val_acc:.2f}%, Macro F1: {epoch_val_f1:.4f}"
        )

        # --- CHECKPOINT SAVING ---
        if epoch_val_f1 > best_val_f1:
            best_val_f1 = epoch_val_f1
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_f1": best_val_f1,
                "val_acc": epoch_val_acc
            }, best_model_path)
            print(f"  --> [SAVED CHECKPOINT] New best Val F1: {best_val_f1:.4f} saved to {best_model_path}")

        # --- EARLY STOPPING CHECK ---
        if early_stopper(epoch_val_f1):
            print(f"\n[EARLY STOPPING TRIGGERED] Training terminated at epoch {epoch}.")
            break

    print("\n" + "=" * 70)
    print(f"Fine-Tuning Complete. Best Validation Macro F1 Score: {best_val_f1:.4f}")
    print("=" * 70)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CBraMod Fine-Tuning Pipeline with Real Preprocessed Data")
    parser.add_argument("--manifest_dir", type=str, required=True, help="Path to directory containing train_manifest.csv and val_manifest.csv")
    parser.add_argument("--epochs", type=int, default=20, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=16, help="Batch size")
    parser.add_argument("--num_channels", type=int, default=64, help="EEG Channel count")
    parser.add_argument("--num_classes", type=int, default=2, help="Number of target classes (2 for binary, 5 for sleep staging)")
    parser.add_argument("--lr_backbone", type=float, default=1e-5, help="Backbone learning rate")
    parser.add_argument("--lr_head", type=float, default=1e-3, help="Classification head learning rate")
    parser.add_argument("--num_workers", type=int, default=4, help="DataLoader CPU workers")

    args = parser.parse_args()

    manifest_dir = Path(args.manifest_dir)
    train_csv = manifest_dir / "train_manifest.csv"
    val_csv = manifest_dir / "val_manifest.csv"

    run_fine_tuning_pipeline(
        train_manifest=train_csv,
        val_manifest=val_csv,
        num_channels=args.num_channels,
        num_classes=args.num_classes,
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr_backbone=args.lr_backbone,
        lr_head=args.lr_head,
        num_workers=args.num_workers
    )