from typing import List, Tuple, Optional, Union, Set
from pathlib import Path
import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import mne
import safetensors
from torch.utils.data import Dataset
from einops.layers.torch import Rearrange
from mne.datasets.sleep_physionet import age

# Import CBraMod architecture from braindecode if available
try:
    from braindecode.models import CBraMod
    HAS_BRAINDECODE = True
except ImportError:
    HAS_BRAINDECODE = False


from typing import List, Tuple, Optional, Union, Set
from pathlib import Path
import json
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset


class RealSleepEEGDataset(Dataset):
    """
    PyTorch Dataset that loads real preprocessed sleep EEG tensors (.npy) 
    using manifest CSVs generated by 03_label_dataset.py.
    
    Reads *_meta.json files to filter out corrupted or flatlined slices 
    ('is_valid': False) and optional sleep stages ('filter_stage') while 
    preserving exact array row index mapping.
    """
    def __init__(
        self,
        manifest_csv: Path,
        data_dir: Optional[Union[str, Path]] = None,
        memory_map: bool = True,
        filter_stage: Optional[Union[str, List[str], Set[str]]] = None
    ):
        self.manifest_csv = Path(manifest_csv)
        self.data_dir = Path(data_dir) if data_dir else None
        self.memory_map = memory_map

        # Parse and standardize optional stage filter (e.g., "N2,N3" or ["N2", "N3"] -> {"N2", "N3"})
        if isinstance(filter_stage, str):
            self.filter_stage: Optional[Set[str]] = {s.strip() for s in filter_stage.split(",")}
        elif isinstance(filter_stage, (list, tuple, set)):
            self.filter_stage = {str(s).strip() for s in filter_stage}
        else:
            self.filter_stage = None

        if not self.manifest_csv.exists():
            raise FileNotFoundError(f"Manifest file not found: {self.manifest_csv}")
            
        self.df = pd.read_csv(self.manifest_csv)
        
        # Index map: (npy_file_path, slice_index_inside_npy, label, subject_id)
        self.samples: List[Tuple[Path, int, int, str]] = []
        self._index_dataset()

    def _index_dataset(self):
        print(f"Indexing samples from manifest: {self.manifest_csv.name}...")
        total_valid_slices = 0
        total_skipped_slices = 0

        for _, row in self.df.iterrows():
            subject_id = str(row["subject_id"])
            raw_npy_path = Path(row["npy_path"])
            raw_meta_path = Path(row["meta_path"]) if "meta_path" in row and pd.notna(row["meta_path"]) else None
            label = int(row["label"])

            if label == -1:
                print(f"  [Warning] Subject {subject_id} missing label, skipping...")
                continue

            # Resolve relative paths against data_dir
            if self.data_dir:
                npy_path = self.data_dir / raw_npy_path if not raw_npy_path.is_absolute() else raw_npy_path
                meta_path = self.data_dir / raw_meta_path if raw_meta_path and not raw_meta_path.is_absolute() else raw_meta_path
            else:
                npy_path = raw_npy_path
                meta_path = raw_meta_path

            if not npy_path.exists():
                print(f"  [Warning] Subject {subject_id} missing tensor file: {npy_path}, skipping...")
                continue

            # Read JSON metadata to unroll valid slices and skip corrupted/flatline/non-matching stage windows
            if meta_path and meta_path.exists():
                try:
                    with open(meta_path, "r") as f:
                        meta = json.load(f)

                    stages_list = meta.get("stages", [])

                    for slice_info in meta.get("slices", []):
                        if not slice_info.get("is_valid", True):
                            total_skipped_slices += 1
                            continue

                        window_idx = slice_info["window_idx"]  # Direct row index in .npy tensor

                        # Resolve stage for current window
                        slice_stage = slice_info.get("stage")
                        if slice_stage is None and window_idx < len(stages_list):
                            slice_stage = stages_list[window_idx]

                        # Apply stage filtering if specified
                        if self.filter_stage is not None and slice_stage not in self.filter_stage:
                            total_skipped_slices += 1
                            continue

                        self.samples.append((npy_path, window_idx, label, subject_id))
                        total_valid_slices += 1
                    continue
                except Exception as e:
                    print(f"  [Warning] Failed to parse meta JSON {meta_path}: {e}. Falling back to array bounds.")

            # Fallback if meta_path is missing
            try:
                if self.memory_map:
                    mmap_data = np.load(npy_path, mmap_mode="r")
                    actual_slices = mmap_data.shape[0]
                else:
                    data = np.load(npy_path)
                    actual_slices = data.shape[0]

                num_slices_manifest = int(row.get("num_slices", actual_slices))
                valid_slices = min(num_slices_manifest, actual_slices)

                for idx in range(valid_slices):
                    self.samples.append((npy_path, idx, label, subject_id))
                    total_valid_slices += 1
            except Exception as e:
                print(f"  [Warning] Subject {subject_id} failed to read tensor from {npy_path}: {e}, skipping...")

        filter_info = f" [Filter Stage: {','.join(sorted(self.filter_stage))}]" if self.filter_stage else ""
        print(
            f"  -> Indexing complete{filter_info}: {total_valid_slices:,} valid windows loaded across {len(self.df)} subjects "
            f"({total_skipped_slices:,} excluded/filtered windows)."
        )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, str]:
        npy_path, window_idx, label, subject_id = self.samples[idx]
        
        # Load single slice from disk using memory-mapping
        if self.memory_map:
            data = np.load(npy_path, mmap_mode="r")
            slice_data = np.array(data[window_idx], dtype=np.float32)
        else:
            data = np.load(npy_path)
            slice_data = data[window_idx].astype(np.float32)

        x_tensor = torch.from_numpy(slice_data)  # Shape: [Channels, Time_Samples]
        y_tensor = torch.tensor(label, dtype=torch.long)
        
        return x_tensor, y_tensor, subject_id


def fetch_and_preprocess_sleep_edf(subject_id: int = 0) -> Tuple[np.ndarray, np.ndarray, float]:
    """
    Downloads a real 8-hour sleep EEG recording from PhysioNet Sleep-EDF,
    resamples to 200 Hz, extracts 30-second epochs, and maps ground-truth sleep stages.
    """
    print(f"--> Fetching real-world Sleep-EDF data for Subject {subject_id} from PhysioNet...")
    [file_path] = age.fetch_data(subjects=[subject_id], recording=[1])
    
    # Load raw EDF recording and corresponding annotations (.edf / .txt)
    raw = mne.io.read_raw_edf(file_path[0], preload=True, verbose=False)
    annot = mne.read_annotations(file_path[1])
    raw.set_annotations(annot, emit_warning=False)

    # Standardize channel configuration and apply 0.5-35 Hz bandpass filter
    raw.filter(l_freq=0.5, h_freq=35.0, verbose=False)

    # Map AASM Sleep Stage annotations to integer target classes
    annotation_mapping = {
        "Sleep stage W": 0,
        "Sleep stage 1": 1,
        "Sleep stage 2": 2,
        "Sleep stage 3": 3,
        "Sleep stage 4": 3,  # Merge N4 into N3 per AASM guidelines
        "Sleep stage R": 4
    }

    # Extract 30-second continuous epochs matching AASM staging
    events, event_id = mne.events_from_annotations(
        raw, event_id=annotation_mapping, chunk_duration=30.0, verbose=False
    )

    tmax = 30.0 - (1.0 / raw.info["sfreq"])
    epochs = mne.Epochs(
        raw,
        events=events,
        event_id=event_id,
        tmin=0.0,
        tmax=tmax,
        baseline=None,
        preload=True,
        verbose=False
    )

    # Resample epochs to CBraMod's target 200 Hz sampling rate
    print("--> Resampling real EEG epochs to 200 Hz...")
    epochs.resample(sfreq=200.0, verbose=False)

    data = epochs.get_data(units="uV")  # Shape: [Epochs, Channels, Time_Samples (6000)]
    labels = epochs.events[:, -1]       # Integer sleep stage labels (0..4)

    return data, labels, epochs.info["sfreq"]


class CBraModRealWorldBenchmark(nn.Module):
    """CBraMod backbone coupled with a 5-class sleep staging head."""
    def __init__(self, num_channels: int, num_patches: int = 30, emb_dim: int = 200, head_dim: int = 128, num_classes: int = 5, dropout: float = 0.3):
        super().__init__()
        if HAS_BRAINDECODE:
            self.backbone = CBraMod.from_pretrained(
                "braindecode/cbramod-pretrained",
                n_chans=num_channels,
                sfreq=200.0,
                return_encoder_output=True
            )

            in_features = num_patches * emb_dim
            self.head = nn.Sequential(
                Rearrange("b s p -> b (s p)"),
                nn.LayerNorm(in_features),
                nn.Linear(in_features, head_dim),
                nn.ELU(),
                nn.Dropout(p=dropout),
                nn.Linear(head_dim, num_classes)
            )
        else:
            # Fallback mock architecture if braindecode package is not installed
            self.backbone = None
            self.head = nn.Sequential(
                nn.Conv1d(num_channels, 64, kernel_size=25, stride=5),
                nn.ReLU(),
                nn.AdaptiveAvgPool1d(10),
                nn.Flatten(),
                nn.Linear(64 * 10, num_classes)
            )

    def forward(self, x):
        if HAS_BRAINDECODE:
            feats = self.backbone(x)
            pooled_feats = feats.mean(dim=1)
            return self.head(pooled_feats)
        else:
            return self.head(x)
