import argparse
from collections import defaultdict
import json
import logging
import re
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import mne
import yasa
import safetensors
from typing import Dict, List, Tuple, Optional, Union, Set
from pathlib import Path
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from einops.layers.torch import Rearrange
from braindecode.models import CBraMod


class PANSleepEEGDataset(Dataset):
    """
    PyTorch Dataset that loads real preprocessed sleep EEG tensors (.npy) 
    using manifest CSVs generated by 03_label_dataset.py.
    
    Reads *_meta.json files to filter out corrupted or flatlined slices 
    ('is_valid': False) and optional sleep stages ('filter_stage') while 
    preserving exact array row index mapping.
    """
    def __init__(
        self,
        manifest_csv: Path,
        data_dir: Optional[Union[str, Path]] = None,
        memory_map: bool = True,
        filter_stage: Optional[Union[str, List[str], Set[str]]] = None
    ):
        self.manifest_csv = Path(manifest_csv)
        self.data_dir = Path(data_dir) if data_dir else None
        self.memory_map = memory_map

        # Parse and standardize optional stage filter (e.g., "N2,N3" or ["N2", "N3"] -> {"N2", "N3"})
        if isinstance(filter_stage, str):
            self.filter_stage: Optional[Set[str]] = {s.strip() for s in filter_stage.split(",")}
        elif isinstance(filter_stage, (list, tuple, set)):
            self.filter_stage = {str(s).strip() for s in filter_stage}
        else:
            self.filter_stage = None

        if not self.manifest_csv.exists():
            raise FileNotFoundError(f"Manifest file not found: {self.manifest_csv}")
            
        self.df = pd.read_csv(self.manifest_csv)
        
        # Index map: (npy_file_path, slice_index_inside_npy, label, subject_id)
        self.samples: List[Tuple[Path, int, int, str]] = []
        self._index_dataset()

    def _index_dataset(self):
        print(f"Indexing samples from manifest: {self.manifest_csv.name}...")
        total_valid_slices = 0
        total_skipped_slices = 0

        for _, row in self.df.iterrows():
            subject_id = str(row["subject_id"])
            raw_npy_path = Path(row["npy_path"])
            raw_meta_path = Path(row["meta_path"]) if "meta_path" in row and pd.notna(row["meta_path"]) else None
            label = int(row["label"])

            if label == -1:
                print(f"  [Warning] Subject {subject_id} missing label, skipping...")
                continue

            # Resolve relative paths against data_dir
            if self.data_dir:
                npy_path = self.data_dir / raw_npy_path if not raw_npy_path.is_absolute() else raw_npy_path
                meta_path = self.data_dir / raw_meta_path if raw_meta_path and not raw_meta_path.is_absolute() else raw_meta_path
            else:
                npy_path = raw_npy_path
                meta_path = raw_meta_path

            if not npy_path.exists():
                print(f"  [Warning] Subject {subject_id} missing tensor file: {npy_path}, skipping...")
                continue

            # Read JSON metadata to unroll valid slices and skip corrupted/flatline/non-matching stage windows
            if meta_path and meta_path.exists():
                try:
                    with open(meta_path, "r") as f:
                        meta = json.load(f)

                    stages_list = meta.get("stages", [])

                    for slice_info in meta.get("slices", []):
                        if not slice_info.get("is_valid", True):
                            total_skipped_slices += 1
                            continue

                        window_idx = slice_info["window_idx"]  # Direct row index in .npy tensor

                        # Resolve stage for current window
                        slice_stage = slice_info.get("stage")
                        if slice_stage is None and window_idx < len(stages_list):
                            slice_stage = stages_list[window_idx]

                        # Apply stage filtering if specified
                        if self.filter_stage is not None and slice_stage not in self.filter_stage:
                            total_skipped_slices += 1
                            continue

                        self.samples.append((npy_path, window_idx, label, subject_id))
                        total_valid_slices += 1
                    continue
                except Exception as e:
                    print(f"  [Warning] Failed to parse meta JSON {meta_path}: {e}. Falling back to array bounds.")

            # Fallback if meta_path is missing
            try:
                if self.memory_map:
                    mmap_data = np.load(npy_path, mmap_mode="r")
                    actual_slices = mmap_data.shape[0]
                else:
                    data = np.load(npy_path)
                    actual_slices = data.shape[0]

                num_slices_manifest = int(row.get("num_slices", actual_slices))
                valid_slices = min(num_slices_manifest, actual_slices)

                for idx in range(valid_slices):
                    self.samples.append((npy_path, idx, label, subject_id))
                    total_valid_slices += 1
            except Exception as e:
                print(f"  [Warning] Subject {subject_id} failed to read tensor from {npy_path}: {e}, skipping...")

        filter_info = f" [Filter Stage: {','.join(sorted(self.filter_stage))}]" if self.filter_stage else ""
        print(
            f"  -> Indexing complete{filter_info}: {total_valid_slices:,} valid windows loaded across {len(self.df)} subjects "
            f"({total_skipped_slices:,} excluded/filtered windows)."
        )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, str]:
        npy_path, window_idx, label, subject_id = self.samples[idx]
        
        # Load single slice from disk using memory-mapping
        if self.memory_map:
            data = np.load(npy_path, mmap_mode="r")
            slice_data = np.array(data[window_idx], dtype=np.float32)
        else:
            data = np.load(npy_path)
            slice_data = data[window_idx].astype(np.float32)

        x_tensor = torch.from_numpy(slice_data)  # Shape: [Channels, Time_Samples]
        y_tensor = torch.tensor(label, dtype=torch.long)
        
        return x_tensor, y_tensor, subject_id


class LinearProbeHead(nn.Module):
    """2-Layer MLP Head with LayerNorm and Dropout."""
    def __init__(
            self,
            num_patches: int = 30, emb_dim: int = 200, hidden_dim: int = 128, num_classes: int = 2, dropout: float = 0.3):
        super().__init__()
        in_features = num_patches * emb_dim

        self.head = nn.Sequential(
            Rearrange("b s p -> b (s p)"),
            nn.LayerNorm(in_features),
            nn.Linear(in_features, hidden_dim),
            nn.ELU(),
            nn.Dropout(p=dropout),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.head(x)


class CBraModE2EClassifier(nn.Module):
    """
    Unified End-to-End Architecture wrapping the CBraMod backbone
    and the LinearProbeHead into a single backward pass graph.
    """
    def __init__(
        self,
        num_channels: int = 64,
        sfreq: float = 200.0,
        num_patches: int = 30,
        emb_dim: int = 200,
        hidden_dim: int = 128,
        num_classes: int = 2,
        dropout: float = 0.3
    ):
        super().__init__()
        self.backbone = CBraMod.from_pretrained(
            "braindecode/cbramod-pretrained",
            n_chans=num_channels,
            sfreq=sfreq,
            return_encoder_output=True
        )
        self.head = LinearProbeHead(
            num_patches=num_patches,
            emb_dim=emb_dim,
            hidden_dim=hidden_dim,
            num_classes=num_classes,
            dropout=dropout
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Backbone output shape: [Batch, Channels, Patches, EmbDim]
        feats = self.backbone(x).mean(dim=1)  # Spatial channel mean -> [Batch, Patches, EmbDim]
        return self.head(feats)


class SyntheticEEGDataset(torch.utils.data.Dataset):
    """
    Generates synthetic EEG tensors matching CBraMod input specs for pipeline verification:
    Shape: [Batch, Channels, Time_Samples] -> [B, 64, 6000] (30s @ 200 Hz)
    """
    def __init__(self, num_samples: int = 128, channels: int = 64, time_samples: int = 6000, num_classes: int = 2):
        self.num_samples = num_samples
        # Generate random Gaussian noise with synthetic 12 Hz sinusoidal bursts (simulated spindles)
        self.data = torch.randn(num_samples, channels, time_samples, dtype=torch.float32)

        # Inject synthetic 12 Hz sine wave in central channels for half the batch
        t = torch.linspace(0, 30, time_samples)
        spindle_wave = 2.0 * torch.sin(2 * np.pi * 12 * t)
        for i in range(num_samples // 2):
            self.data[i, :4, 2000:2400] += spindle_wave[2000:2400] # Inject 2-second burst

        self.labels = torch.cat([torch.ones(num_samples // 2, dtype=torch.long),
                                 torch.zeros(num_samples - num_samples // 2, dtype=torch.long)])

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]


class CBraModFeatureExtractor(nn.Module):
    """Backbone extractor that channel-pools [B, C, S, P] -> [B, S, P]."""
    def __init__(self, num_channels: int = 64, sfreq: float = 200.0):
        super().__init__()
        self.backbone = CBraMod.from_pretrained(
            "braindecode/cbramod-pretrained",
            n_chans=num_channels,
            sfreq=sfreq,
            return_encoder_output=True
        )

    @torch.no_grad()
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        feats = self.backbone(x)
        return feats.mean(dim=1)


def compute_pooled_scores(
    window_probs: np.ndarray,
    method: str = "p85_score",
    top_percentile: float = 0.10,
    t_window: float = 0.60
) -> Union[float, np.ndarray]:
    """
    Aggregates window-level probabilities into subject-level class scores.
    Supports both 1D arrays (binary positive class probabilities) and 
    2D arrays (shape: [Num_Windows, Num_Classes]).

    Args:
        window_probs: Array of probabilities [N] or [N, K].
        method: Pooling strategy ('p85_score', 'top_10_mean', 'trimmed_top_10', 'burden_ratio').
        top_percentile: Fraction of top windows to evaluate (default: 0.10).
        t_window: Window-level probability threshold for burden ratio.

    Returns:
        float if 1D input (binary), or np.ndarray [K] if 2D input (multi-class).
    """
    if len(window_probs) == 0:
        return 0.0 if window_probs.ndim == 1 else np.array([])

    is_1d = (window_probs.ndim == 1)
    N = len(window_probs)
    k_len = max(1, int(np.ceil(N * top_percentile)))

    if method == "p85_score":
        if is_1d:
            return float(np.percentile(window_probs, 85))
        return np.percentile(window_probs, 85, axis=0)

    elif method == "top_10_mean":
        if is_1d:
            sorted_p = np.sort(window_probs)[::-1]
            return float(np.mean(sorted_p[:k_len]))
        sorted_p = np.sort(window_probs, axis=0)[::-1, :]
        return np.mean(sorted_p[:k_len, :], axis=0)

    elif method == "trimmed_top_10":
        skip = int(N * 0.02)
        if is_1d:
            sorted_p = np.sort(window_probs)[::-1]
            return float(np.mean(sorted_p[skip : skip + k_len]))
        sorted_p = np.sort(window_probs, axis=0)[::-1, :]
        return np.mean(sorted_p[skip : skip + k_len, :], axis=0)

    elif method == "burden_ratio":
        if is_1d:
            return float(np.mean(window_probs >= t_window))
        # Multi-class burden: proportion of windows where class k is argmax and >= t_window
        dominant_class = np.argmax(window_probs, axis=1)
        K = window_probs.shape[1]
        scores = np.zeros(K, dtype=np.float64)
        for c in range(K):
            scores[c] = np.mean((dominant_class == c) & (window_probs[:, c] >= t_window))
        return scores

    else:
        raise ValueError(f"Unsupported pooling method: {method}")


# Standard sleep stage string normalization map
STAGE_NORM_MAP = {
    "sleep stage w": "W", "stage w": "W", "wake": "W", "0": "W",
    "sleep stage n1": "N1", "stage 1": "N1", "n1": "N1", "1": "N1",
    "sleep stage n2": "N2", "stage 2": "N2", "n2": "N2", "2": "N2",
    "sleep stage n3": "N3", "stage 3": "N3", "stage 4": "N3", "n3": "N3", "3": "N3", "4": "N3",
    "sleep stage r": "REM", "stage rem": "REM", "rem": "REM", "5": "REM"
}


def extract_epoch_stages(raw: mne.io.BaseRaw, num_windows: int, window_sec: float = 30.0) -> List[str]:
    """Parses annotations for sleep stage labels."""
    if len(raw.annotations) == 0:
        return ["UNKNOWN"] * num_windows

    stages = []
    annotations = raw.annotations

    for idx in range(num_windows):
        t_mid = (idx * window_sec) + (window_sec / 2.0)
        stage_label = "UNKNOWN"

        for ann in annotations:
            ann_start = ann["onset"]
            ann_end = ann_start + ann["duration"]
            if ann_start <= t_mid < ann_end:
                raw_desc = str(ann["description"]).strip().lower()
                stage_label = STAGE_NORM_MAP.get(raw_desc, ann["description"])
                break

        stages.append(stage_label)

    return stages


def select_best_eeg_channel(eeg_chs: List[str]) -> str:
    """Selects central channel for YASA."""
    preferences = ["C4", "C3", "CZ"]
    for pref in preferences:
        pattern = re.compile(rf"\b{pref}\b", re.IGNORECASE)
        for ch in eeg_chs:
            if pattern.search(ch):
                return ch
    return eeg_chs[0]


def predict_epoch_stages_yasa(raw: mne.io.BaseRaw, num_windows: int) -> List[str]:
    """YASA fallback predictor."""
    try:
        eeg_chs = raw.copy().pick('eeg').ch_names
        if not eeg_chs:
            eeg_chs = raw.ch_names
        target_ch = select_best_eeg_channel(eeg_chs)

        sls = yasa.SleepStaging(raw, eeg_name=target_ch)
        stages = list(sls.predict().hypno)

        if len(stages) < num_windows:
            stages.extend(["UNKNOWN"] * (num_windows - len(stages)))
        elif len(stages) > num_windows:
            stages = stages[:num_windows]

        return stages
    except Exception:
        return ["UNKNOWN"] * num_windows


def setup_data_loader_and_criterion(
    dataset: Dataset,
    labels: np.ndarray,
    batch_size: int,
    num_workers: int,
    imbalance_strategy: str,
    device: torch.device,
    logger: logging.Logger
) -> Tuple[DataLoader, nn.Module]:
    """
    Configures training DataLoader and CrossEntropyLoss based on imbalance strategy.

    Strategies:
      - 'sampler': Uses WeightedRandomSampler to balance batch draws. Unweighted CrossEntropyLoss.
      - 'loss_weights': Standard DataLoader with shuffle=True. Inverse class frequency weighted CrossEntropyLoss.
      - 'none': Standard DataLoader with shuffle=True and unweighted CrossEntropyLoss.
    """
    class_counts = np.bincount(labels)
    total_samples = len(labels)
    num_classes = len(class_counts)

    logger.info("--- Training Set Class Distribution ---")
    for class_id, count in enumerate(class_counts):
        pct = (count / total_samples) * 100.0 if total_samples > 0 else 0.0
        logger.info(f"  Class {class_id}: {count:,} samples ({pct:.2f}%)")

    persistent_workers = num_workers > 0

    if imbalance_strategy == "sampler":
        logger.info("--> Imbalance Strategy: WeightedRandomSampler (Resampling minority class batches)")
        class_weights_raw = 1.0 / np.maximum(class_counts, 1)
        sample_weights = class_weights_raw[train_labels]
        sampler = WeightedRandomSampler(
            weights=torch.from_numpy(sample_weights).double(),
            num_samples=len(sample_weights),
            replacement=True
        )
        train_loader = DataLoader(
            dataset, batch_size=batch_size, sampler=sampler, num_workers=num_workers,
            pin_memory=True, persistent_workers=persistent_workers
        )
        criterion = nn.CrossEntropyLoss()

    elif imbalance_strategy == "loss_weights":
        logger.info("--> Imbalance Strategy: Class-Weighted CrossEntropyLoss")
        balanced_weights = total_samples / (num_classes * np.maximum(class_counts, 1).astype(np.float32))
        weights_tensor = torch.from_numpy(balanced_weights).float().to(device)

        weight_str = ", ".join([f"Class {i}: {w:.4f}" for i, w in enumerate(balanced_weights)])
        logger.info(f"    Derived Loss Weights: [{weight_str}]")

        criterion = nn.CrossEntropyLoss(weight=weights_tensor)
        train_loader = DataLoader(
            dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers,
            pin_memory=True, persistent_workers=persistent_workers
        )

    elif imbalance_strategy == "none":
        logger.info("--> Imbalance Strategy: None (Unweighted training)")
        criterion = nn.CrossEntropyLoss()
        train_loader = DataLoader(
            dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers,
            pin_memory=True, persistent_workers=persistent_workers
        )

    else:
        raise ValueError(f"Invalid imbalance strategy: {imbalance_strategy}. Choose 'sampler', 'loss_weights', or 'none'.")

    return train_loader, criterion


def evaluate_subject_quality(
    meta: dict,
    max_rejection_rate: float = 0.15,
    max_n3_rejection_rate: float = 0.10,
    min_valid_hours: float = 4.5,
    window_duration_sec: float = 30.0
) -> Tuple[bool, dict, str]:
    """
    Evaluates slice-level metadata for quality screening and subject acceptance.

    Checks:
    1. Overall window rejection rate <= max_rejection_rate
    2. N3 stage window rejection rate <= max_n3_rejection_rate
    3. Total usable sleep duration >= min_valid_hours
    """
    slices = meta.get("slices", [])
    stages = meta.get("stages", [])
    total_slices = meta.get("num_slices", len(slices))

    if total_slices == 0:
        return False, {}, "EMPTY_RECORDING"

    # Extract or infer slice validity
    if slices:
        valid_mask = [s.get("is_valid", True) for s in slices]
    else:
        # Fallback if slice details are omitted
        valid_mask = [True] * total_slices

    total_valid = sum(valid_mask)
    total_invalid = total_slices - total_valid
    overall_rejection_rate = total_invalid / float(total_slices)
    valid_hours = (total_valid * window_duration_sec) / 3600.0

    # Calculate N3 stage specific rejection rate if stage data is present
    n3_rejection_rate = 0.0
    if stages and len(stages) == len(valid_mask):
        n3_pairs = [(v, st) for v, st in zip(valid_mask, stages) if str(st).upper() == "N3"]
        if n3_pairs:
            n3_total = len(n3_pairs)
            n3_invalid = sum(1 for v, _ in n3_pairs if not v)
            n3_rejection_rate = n3_invalid / float(n3_total)

    # Evaluate Gatekeeping Rules
    reasons = []
    if overall_rejection_rate > max_rejection_rate:
        reasons.append(f"HIGH_REJECTION_RATE ({overall_rejection_rate:.1%})")
    if n3_rejection_rate > max_n3_rejection_rate:
        reasons.append(f"HIGH_N3_REJECTION ({n3_rejection_rate:.1%})")
    if valid_hours < min_valid_hours:
        reasons.append(f"INSUFFICIENT_SLEEP_DURATION ({valid_hours:.2f}h)")

    is_accepted = len(reasons) == 0
    reason_str = "PASSED" if is_accepted else "; ".join(reasons)

    metrics = {
        "total_slices": total_slices,
        "valid_slices": total_valid,
        "invalid_slices": total_invalid,
        "overall_rejection_rate": round(overall_rejection_rate, 4),
        "n3_rejection_rate": round(n3_rejection_rate, 4),
        "valid_sleep_hours": round(valid_hours, 2),
        "gatekeeping_status": "ACCEPTED" if is_accepted else "REJECTED",
        "rejection_reason": reason_str
    }

    return is_accepted, metrics, reason_str

class CBraModTrainer:
    """Base class for training CBraMod models with subject-level evaluation."""
    def __init__(self, config: argparse.Namespace, logger: logging.Logger):
        self.config = config
        self.logger = logger
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def evaluate_subject_pooling(
        self, 
        val_probs: np.ndarray, 
        val_targets: np.ndarray, 
        val_subject_ids: List[str]
    ) -> Dict[str, Dict[str, float]]:
        """
        Groups window probabilities by subject using an O(N) pre-indexed map, 
        applies all 4 pooling strategies, and performs threshold tuning.
        """
        strategies = ["p85_score", "top_10_mean", "trimmed_top_10", "burden_ratio"]

        # O(N) linear indexing pass to pre-group window indices by subject ID
        subj_to_indices = defaultdict(list)
        for idx, subj in enumerate(val_subject_ids):
            subj_to_indices[subj].append(idx)

        subject_data = {strat: [] for strat in strategies}
        subject_labels = []

        # Iterate through pre-grouped subject slices
        for subj, idxs in subj_to_indices.items():
            idx_arr = np.array(idxs, dtype=np.int64)
            subj_probs = val_probs[idx_arr]
            subj_gt = val_targets[idx_arr[0]]
            subject_labels.append(subj_gt)

            for strat in strategies:
                if self.config.num_classes == 2:
                    score = compute_pooled_scores(
                        subj_probs[:, 1], 
                        method=strat, 
                        top_percentile=self.config.top_percentile, 
                        t_window=self.config.t_window
                    )
                else:
                    score = compute_pooled_scores(
                        subj_probs, 
                        method=strat, 
                        top_percentile=self.config.top_percentile, 
                        t_window=self.config.t_window
                    )
                subject_data[strat].append(score)

        subject_labels = np.array(subject_labels)
        results = {}

        # Strategy evaluation and threshold optimization
        for strat in strategies:
            scores = np.array(subject_data[strat])
            
            if self.config.num_classes == 2:
                # Binary threshold sweep to maximize Macro F1 on Subject predictions
                best_t = 0.5
                best_f1 = 0.0
                thresholds = np.linspace(0.01, 0.99, 99)
                
                for t in thresholds:
                    preds = (scores >= t).astype(int)
                    f1 = f1_score(subject_labels, preds, average="macro", zero_division=0)
                    if f1 > best_f1:
                        best_f1 = f1
                        best_t = t
                
                final_preds = (scores >= best_t).astype(int)
                acc = accuracy_score(subject_labels, final_preds)
                roc_auc = roc_auc_score(subject_labels, scores) if len(np.unique(subject_labels)) > 1 else 0.5

                results[strat] = {
                    "subject_macro_f1": best_f1,
                    "optimal_threshold": float(best_t),
                    "subject_accuracy": acc,
                    "roc_auc": roc_auc
                }
            else:
                # Multi-class argmax selection
                preds = np.argmax(scores, axis=1)
                macro_f1 = f1_score(subject_labels, preds, average="macro", zero_division=0)
                acc = accuracy_score(subject_labels, preds)
                results[strat] = {
                    "subject_macro_f1": macro_f1,
                    "optimal_threshold": 0.5,
                    "subject_accuracy": acc,
                    "roc_auc": 0.5
                }

        return results  

    def train(self, train_path: Path, val_path: Path):
        pass  # Placeholder for training loop implementation  


def setup_pipeline_cli_parser(
    description: str = "CBraMod Pipeline"
) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    # CBraMod Architecture Controls    
    cbra_group = parser.add_argument_group("CBraMod Architecture Controls")
    cbra_group.add_argument("--num-channels", type=int, default=64, help="EEG Channel count")
    cbra_group.add_argument("--num-patches", type=int, default=30, help="Number of temporal patches in CBraMod")
    cbra_group.add_argument("--sfreq", type=float, default=200.0, help="EEG sampling frequency")
    cbra_group.add_argument("--num-classes", type=int, default=2, help="Number of target classes")

    # Manifest & Data Paths
    data_group = parser.add_argument_group("Data Sources")
    data_group.add_argument("--train-manifest", type=str, default=None, help="Path to training manifest file (CSV/TSV/JSON)")
    data_group.add_argument("--val-manifest", type=str, default=None, help="Path to validation manifest file (CSV/TSV/JSON)")
    data_group.add_argument("--data-dir", type=str, default=None, help="Root directory containing .npy files")

    # Imbalance & Stage Controls
    strat_group = parser.add_argument_group("Imbalance & Stage Controls")
    strat_group.add_argument(
        "--imbalance-strategy",
        type=str,
        choices=["sampler", "loss_weights", "none"],
        default="loss_weights",
        help="Class imbalance handling: 'sampler' (WeightedRandomSampler), 'loss_weights' (Class-Weighted CrossEntropy), or 'none'"
    )
    strat_group.add_argument("--filter-stage", type=str, default="N2,N3", help="Comma-separated sleep stages to pass into PANSleepEEGDataset (e.g., N2,N3)")

    # Pooling Configurations
    pool_group = parser.add_argument_group("Subject-Level Pooling Options")
    pool_group.add_argument(
        "--primary-pooling",
        type=str,
        default="p85_score",
        choices=["p85_score", "top_10_mean", "trimmed_top_10", "burden_ratio"],
        help="Primary pooling strategy used for early stopping and model selection"
    )
    pool_group.add_argument("--top-percentile", type=float, default=0.10, help="Top percentile ratio for top-K pooling methods")
    pool_group.add_argument("--t-window", type=float, default=0.60, help="Window threshold for pathology burden ratio")

    # Hyperparameters
    hp_group = parser.add_argument_group("Common Hyperparameters")
    hp_group.add_argument("--epochs", type=int, default=40, help="Maximum training epochs for linear probe head")
    hp_group.add_argument("--batch-size", type=int, default=512, help="Batch size for training and feature extraction")
    hp_group.add_argument("--head-lr", type=float, default=1e-4, help="Initial learning rate for classification head")
    hp_group.add_argument("--min-lr", type=float, default=1e-6, help="Minimum learning rate for Cosine Annealing scheduler")
    hp_group.add_argument("--weight-decay", type=float, default=1e-2, help="AdamW weight decay regularizer")
    hp_group.add_argument("--hidden-dim", type=int, default=128, help="Bottleneck linear layer dimension")
    hp_group.add_argument("--dropout", type=float, default=0.3, help="Dropout probability in head")

    # System Controls
    sys_group = parser.add_argument_group("System Controls")
    sys_group.add_argument("--num-workers", type=int, default=4, help="DataLoader CPU workers for disk reads")
    sys_group.add_argument("--seed", type=int, default=42, help="Random seed for deterministic execution")
    sys_group.add_argument("--patience", type=int, default=10, help="Early stopping patience (epochs without Subject F1 improvement)")
    sys_group.add_argument("--no-amp", action="store_true", help="Disable Automatic Mixed Precision (AMP)")
    sys_group.add_argument("--log-filename", type=str, default=__file__.replace(".py", ".log"), help="Filename for pipeline log output")

    return parser