"""
p09k_absolute_band_power_analysis.py

Absolute-power counterpart to p09f_morphology_score_correlation.py / p09j_band_covariation_check.py.
Both of those operate on RELATIVE band power (each band's share of a window's total power, a
composition that sums to ~1 by construction) -- which p09j confirmed is tightly bound (relpower sum
= 1.027 +/- 0.020) and shows the exact signature of "one dominant component (delta) vs. a co-moving
shared remainder" (the four non-delta bands correlate +0.72 to +0.92 with EACH OTHER, while each
correlates -0.89 to -0.95 with delta). That pattern is guaranteed in RATIO space regardless of what's
actually happening physically -- it carries no information about whether real, absolute (uV^2) delta
power rises together with the other bands (a shared broadband amplitude/state factor) or trades off
against them (a genuine spectral trade-off). Only absolute power can distinguish those.

This script reconstructs the real uV signal for every window using the per-channel norm_mean_uv/
norm_std_uv persisted by p02_slice_eeg_dataset.py's process_and_normalize_slice() (needs metadata
regenerated by a p02 re-slice that includes this field -- an older meta_path without these keys
raises an explicit error rather than silently falling back to the Z-scored signal, which would
silently defeat the entire point of this script), then:
  1. Computes ABSOLUTE Welch band power (raw PSD-bin sum, no normalization by total -- so these are
     in consistent-but-uncalibrated units proportional to uV^2, not a physically calibrated uV^2/Hz;
     fine for correlation purposes since every window is computed identically) for the same 5 bands.
  2. Re-runs YASA spindle/slow-wave detection on the reconstructed real-uV signal instead of the
     Z-scored one -- YASA's detectors are calibrated against real EEG amplitude, so this should also
     fix the amplitude-related warnings seen running YASA on Z-scored data earlier in this
     investigation ("Wrong data amplitude... trimmed STD = 0.000").
  3. Correlates probability against ABSOLUTE band power (pooled + within-subject) -- the direct
     re-test of whether delta's earlier positive relationship (found using relative power) survives,
     flips, or vanishes once expressed in real, non-ratio-constrained units.
  4. Correlates delta_abspower against each other band's abspower (pooled + within-subject) -- the
     direct test of the open question: do they co-move (shared broadband factor) or trade off (a
     real spectral relationship)? Unlike the relpower version, this one is NOT guaranteed to come out
     any particular way by construction -- absolute powers have no sum-to-1 constraint.

Usage:
  python p09k_absolute_band_power_analysis.py \
      --checkpoint model.pt --manifest test_manifest.csv \
      --output-dir results/ --max-windows-per-subject 200
"""

import argparse
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from scipy.signal import welch
from tqdm import tqdm

try:
    import yasa
    HAS_YASA = True
    # yasa's "No spindles/SW were found..." messages are emitted via the logging module at WARNING
    # level regardless of the verbose=False passed to spindles_detect()/sw_detect() below -- that kwarg
    # only gates yasa's own INFO-ish prints. Most windows legitimately contain zero detected events
    # (spindles/slow-waves are transient, not present in every 30s window), so this is expected,
    # benign output, not a data-quality signal.
    #
    # A per-logger logging.getLogger("yasa").setLevel(logging.ERROR) does NOT reliably silence this --
    # yasa's own verbose=False handling appears to reset its logger's level back to WARNING internally
    # on every spindles_detect()/sw_detect() call, undoing a one-time setLevel from here. logging.
    # disable() instead sets a GLOBAL threshold checked independently of any individual logger's own
    # level (Logger.manager.disable), so it can't be undone by yasa resetting its own logger per-call.
    # ERROR (40) and CRITICAL stay visible; only WARNING (30) and below are suppressed.
    logging.disable(logging.WARNING)
except ImportError:
    HAS_YASA = False

from cbramod_common import (
    BAND_DEFS,
    PANSubjectEEGDataset,
    add_log_filename_argument,
    build_frozen_e2e_classifier,
    extract_ckpt_metadata,
    resolve_pooling_config,
    seed_everything,
    setup_inference_cli_parser,
)
from cbramod_utils import setup_logger
from p09c_clinical_subject_diagnostics import SubjectEEGInspector, load_subject_ids_from_json


def load_norm_stats_by_window_idx(meta_path: Path) -> Dict[int, Tuple[np.ndarray, np.ndarray]]:
    """
    Maps window_idx -> (norm_mean_uv, norm_std_uv) per-channel arrays, read directly from a p02
    meta_path JSON's "slices" list. Raises KeyError (not a silent fallback) if a slice is missing
    these keys -- an older meta_path predating the p02 norm_mean_uv/norm_std_uv change would silently
    produce garbage "reconstructed" signal (0 uV everywhere) rather than a clear error, which would
    defeat the entire point of this script without necessarily failing loudly downstream.
    """
    with open(meta_path, "r") as f:
        meta = json.load(f)
    stats_by_idx = {}
    for slice_info in meta.get("slices", []):
        if not slice_info.get("is_valid", True):
            continue
        if "norm_mean_uv" not in slice_info or "norm_std_uv" not in slice_info:
            raise KeyError(
                f"{meta_path} slice window_idx={slice_info.get('window_idx')} is missing "
                f"norm_mean_uv/norm_std_uv -- this meta_path predates the p02 change that persists "
                f"them. Re-run p02 slicing (metadata only needs regenerating, not the .npy tensors) "
                f"and point --manifest/--data-dir at the updated metadata before running this script."
            )
        stats_by_idx[slice_info["window_idx"]] = (
            np.array(slice_info["norm_mean_uv"], dtype=np.float32),
            np.array(slice_info["norm_std_uv"], dtype=np.float32),
        )
    return stats_by_idx


def reconstruct_real_uv_channel_mean(
    normalized_CT: np.ndarray, norm_mean_uv: np.ndarray, norm_std_uv: np.ndarray
) -> np.ndarray:
    """
    Inverts p02's per-channel Z-score normalization (exact, same epsilon) then averages across
    ACTIVE channels only (norm_std_uv > 0 -- p02 leaves this at exactly 0.0 for zero-padded/inactive
    channels, since they're never normalized at all) in real uV -- a physically meaningful "overall
    signal amplitude" proxy, unlike averaging the Z-scored signal the model itself pools (which
    discards each channel's real amplitude scale before averaging) or averaging across all 64
    channels including zero-padding.

    Averaging over all 64 (as p09f/p09h/p09i do for the Z-scored signal) is harmless for RELATIVE
    power -- a subject with only 20 of 64 channels recorded gets a uniformly diluted signal
    (~20/64 the amplitude), but that's a single scalar factor on the whole window that cancels
    exactly in a ratio. It is NOT harmless for ABSOLUTE power (this script's whole point): that same
    dilution factor differs subject-to-subject depending on how many channels they had recorded,
    confounding any cross-subject absolute-power comparison with an artifact of channel count rather
    than real signal. It also explains YASA's "Wrong data amplitude... trimmed STD = 0.000" spam --
    a signal diluted by zero-padding can fall below YASA's amplitude sanity floor even when the real,
    active-channel signal is a perfectly normal EEG amplitude.
    """
    active_mask = norm_std_uv > 0
    if not np.any(active_mask):
        # Shouldn't happen for a valid window (p02 rejects all-zero windows outright), but don't
        # silently divide by zero -- fall back to the diluted all-channel mean rather than crash.
        real_uv_CT = normalized_CT * (norm_std_uv[:, None] + 1e-8) + norm_mean_uv[:, None]
        return real_uv_CT.mean(axis=0)
    real_uv_CT_active = (
        normalized_CT[active_mask] * (norm_std_uv[active_mask, None] + 1e-8) + norm_mean_uv[active_mask, None]
    )
    return real_uv_CT_active.mean(axis=0)


def compute_band_powers(signal_1d: np.ndarray, sfreq: float, prefix: str) -> Dict[str, float]:
    """Welch band power (both absolute raw-sum and relative-to-total, for a direct side-by-side)."""
    freqs, psd = welch(signal_1d, fs=sfreq, nperseg=min(len(signal_1d), int(sfreq * 4)))
    total_mask = (freqs >= 0.5) & (freqs <= 30.0)
    total_power = psd[total_mask].sum()
    powers = {}
    for band, (lo, hi) in BAND_DEFS.items():
        mask = (freqs >= lo) & (freqs <= hi)
        band_power = float(psd[mask].sum())
        powers[f"{band}_{prefix}abspower"] = band_power
        powers[f"{band}_{prefix}relpower"] = band_power / total_power if total_power > 0 else 0.0
    return powers


def compute_yasa_event_counts(signal_1d: np.ndarray, sfreq: float) -> Dict[str, float]:
    """Spindle/slow-wave counts on the reconstructed real-uV signal (0 if unavailable/none detected)."""
    n_spindles, n_slow_waves = 0, 0
    if HAS_YASA:
        try:
            sp = yasa.spindles_detect(signal_1d, sf=sfreq, freq_sp=(11, 16), verbose=False)
            n_spindles = len(sp.summary()) if sp is not None else 0
        except Exception:
            pass
        try:
            sw = yasa.sw_detect(signal_1d, sf=sfreq, verbose=False)
            n_slow_waves = len(sw.summary()) if sw is not None else 0
        except Exception:
            pass
    return {"n_spindles": float(n_spindles), "n_slow_waves": float(n_slow_waves)}


def spearman_corr(a: np.ndarray, b: np.ndarray) -> float:
    a, b = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    if len(a) < 3 or np.std(a) == 0 or np.std(b) == 0:
        return float("nan")
    ra = np.argsort(np.argsort(a)).astype(np.float64)
    rb = np.argsort(np.argsort(b)).astype(np.float64)
    return float(np.corrcoef(ra, rb)[0, 1])


def parse_cli_args() -> argparse.Namespace:
    parser = setup_inference_cli_parser(description="Absolute Band Power vs. Window Score / Cross-Band Covariation")
    group = parser.add_argument_group("Absolute Band Power Analysis")
    group.add_argument(
        "--max-windows-per-subject", type=int, default=None,
        help="Randomly subsample to at most this many windows per subject. Default: use every valid window."
    )
    group.add_argument(
        "--subjects-json", type=str, default=None,
        help="Path to a p09d_subject_confidence_report.py --output-json report. Its subject_ids are "
             "unioned with --subject-id (if also given) to select which subjects to analyze."
    )
    group.add_argument(
        "--output-csv", type=str, default="absolute_band_power_analysis.csv",
        help="Filename (relative to --output-dir) for the full per-window feature table."
    )
    add_log_filename_argument(parser, __file__)
    return parser.parse_args()


def main():
    args = parse_cli_args()
    logger = setup_logger(args.log_filename)
    seed_everything(args.seed)
    rng = np.random.RandomState(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    output_dir = Path(args.output_dir) if args.output_dir else Path("./absolute_band_power_analysis_results")
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.features_pt:
        raise ValueError(
            "This script needs raw EEG (--manifest) to reconstruct real uV and compute band power/YASA "
            "features from the signal itself; --features-pt (pre-extracted embeddings) has no raw "
            "waveform (or normalization metadata) left to work with."
        )

    model, ckpt = build_frozen_e2e_classifier(args, device, logger)
    _thresholds, _epoch, ckpt_pooling_params = extract_ckpt_metadata(ckpt)

    pooling_strategy, top_percentile, t_window = resolve_pooling_config(
        pooling_strategy=args.pooling_strategy, top_percentile=args.top_percentile,
        t_window=args.t_window, ckpt_pooling_params=ckpt_pooling_params
    )
    print(
        f"Pooling config: strategy={pooling_strategy}, top_percentile={top_percentile}, t_window={t_window} "
        f"(source: {'CLI override' if args.pooling_strategy is not None else 'checkpoint/default'})"
    )
    inspector = SubjectEEGInspector(model=model, device=device, threshold=0.5)

    subject_filter = [s.strip() for s in args.subject_id.split(",")] if args.subject_id else []
    if args.subjects_json:
        json_subject_ids = load_subject_ids_from_json(Path(args.subjects_json))
        print(f"Loaded {len(json_subject_ids)} subject_id(s) from --subjects-json: {args.subjects_json}")
        subject_filter = subject_filter + [sid for sid in json_subject_ids if sid not in subject_filter]
    subject_filter = subject_filter or None

    dataset = PANSubjectEEGDataset(
        manifest_csv=args.manifest, data_dir=args.data_dir, filter_stage=args.filter_stage,
        filter_subject=subject_filter, memory_map=True
    )
    print(f"Loaded raw EEG recording dataset for {len(dataset)} subjects.")

    if not HAS_YASA:
        print("  [Warning] YASA not installed -- n_spindles/n_slow_waves will be 0 for every window.")

    # meta_path per subject, resolved exactly like PANSubjectEEGDataset._index_dataset resolves it --
    # needed here (and only here) to pull norm_mean_uv/norm_std_uv, which the dataset itself doesn't expose.
    manifest_df = pd.read_csv(args.manifest)
    manifest_df["subject_id"] = manifest_df["subject_id"].astype(str)
    data_dir = Path(args.data_dir) if args.data_dir else None
    meta_path_by_subject: Dict[str, Optional[Path]] = {}
    for _, row in manifest_df.iterrows():
        raw_meta_path = Path(row["meta_path"]) if "meta_path" in row and pd.notna(row["meta_path"]) else None
        if raw_meta_path is None:
            meta_path_by_subject[str(row["subject_id"])] = None
        else:
            meta_path_by_subject[str(row["subject_id"])] = (
                data_dir / raw_meta_path if data_dir and not raw_meta_path.is_absolute() else raw_meta_path
            )

    all_rows: List[Dict] = []
    skipped_no_meta = 0
    for idx in tqdm(range(len(dataset)), desc="Process Subjects"):
        x_tensor, y_tensor, subj_id, stages, indices = dataset[idx]
        if x_tensor.shape[0] == 0:
            print(f"Skipping {subj_id}: No valid windows after stage filtering.")
            continue

        meta_path = meta_path_by_subject.get(subj_id)
        if meta_path is None or not meta_path.exists():
            print(f"  [Warning] Skipping {subj_id}: no meta_path available, can't reconstruct real uV.")
            skipped_no_meta += 1
            continue
        norm_stats_by_idx = load_norm_stats_by_window_idx(meta_path)

        report = inspector.inspect_subject(
            x_tensor=x_tensor, subject_id=subj_id, ground_truth=y_tensor.item(),
            stages=stages, indices=indices, pooling_strategy=pooling_strategy,
            top_percentile=top_percentile, t_window=t_window, batch_size=args.batch_size
        )

        num_windows = x_tensor.shape[0]
        window_order = np.arange(num_windows)
        if args.max_windows_per_subject and num_windows > args.max_windows_per_subject:
            window_order = rng.choice(num_windows, size=args.max_windows_per_subject, replace=False)

        raw_np = x_tensor.numpy()  # [N, C, T], Z-scored, same window order as report["window_probs"]/["indices"]
        for f_idx in window_order:
            window_idx = int(report["indices"][f_idx])
            if window_idx not in norm_stats_by_idx:
                continue  # shouldn't happen for a valid window, but skip rather than crash on a mismatch
            norm_mean_uv, norm_std_uv = norm_stats_by_idx[window_idx]

            real_uv_signal = reconstruct_real_uv_channel_mean(raw_np[f_idx], norm_mean_uv, norm_std_uv)
            zscore_signal = raw_np[f_idx].mean(axis=0)  # for a direct real-vs-Z-scored sanity comparison

            real_powers = compute_band_powers(real_uv_signal, args.sfreq, prefix="real_")
            zscore_powers = compute_band_powers(zscore_signal, args.sfreq, prefix="zscore_")
            yasa_counts = compute_yasa_event_counts(real_uv_signal, args.sfreq)

            all_rows.append({
                "subject_id": subj_id,
                "ground_truth": report["ground_truth"],
                "raw_epoch_index": window_idx,
                "stage": report["stages"][f_idx] if f_idx < len(report["stages"]) else "UNKNOWN",
                "probability": float(report["window_probs"][f_idx]),
                **real_powers,
                **zscore_powers,
                **yasa_counts,
            })

    if skipped_no_meta:
        print(f"\n[Warning] Skipped {skipped_no_meta} subject(s) entirely for lacking usable meta_path.")
    if not all_rows:
        print("No windows collected -- nothing to analyze.")
        return

    df = pd.DataFrame(all_rows)
    csv_path = output_dir / args.output_csv
    df.to_csv(csv_path, index=False)
    print(f"\nSaved {len(df)} window-level rows across {df['subject_id'].nunique()} subjects to: {csv_path}")

    abspower_cols = [f"{band}_real_abspower" for band in BAND_DEFS]
    relpower_cols_real = [f"{band}_real_relpower" for band in BAND_DEFS]
    relpower_cols_zscore = [f"{band}_zscore_relpower" for band in BAND_DEFS]

    print("\n" + "=" * 88)
    print("0) SANITY CHECK: real-uV relpower vs. Z-scored relpower (p09f used the Z-scored version)")
    print("=" * 88)
    print(
        "Relative power SHOULD be near-invariant to a uniform per-window rescale, but real-uV channel-"
        "mean and Z-scored channel-mean are NOT the same signal (each channel is rescaled by a "
        "DIFFERENT factor before averaging in the real-uV case) -- so these can legitimately differ. "
        "Large, systematic differences would mean the two pipelines are answering subtly different "
        "questions about \"the channel-mean signal\", worth knowing before trusting either one alone."
    )
    for band in BAND_DEFS:
        r = spearman_corr(df[f"{band}_real_relpower"].values, df[f"{band}_zscore_relpower"].values)
        print(f"  Spearman({band}_real_relpower, {band}_zscore_relpower) = {r:+.4f}")

    print("\n" + "=" * 88)
    print("1) PROBABILITY vs. ABSOLUTE BAND POWER (the direct re-test of p09f's relative-power finding)")
    print("=" * 88)
    report_correlations(df, abspower_cols, "probability vs absolute power")

    print("\n" + "=" * 88)
    print("2) CROSS-BAND COVARIATION IN ABSOLUTE POWER (does delta co-move with the others, or trade off?)")
    print("=" * 88)
    print(
        "Unlike relative power (which is compositionally constrained to show this pattern regardless of "
        "physiology), absolute power has NO sum-to-1 constraint -- whatever correlation structure shows "
        "up here is real, not guaranteed by construction."
    )
    report_pairwise(df, abspower_cols, "ALL WINDOWS, POOLED")
    report_pairwise_within_subject(df, abspower_cols)

    print("\n" + "=" * 88)
    print("3) PROBABILITY vs. YASA MORPHOLOGY EVENT COUNTS (spindles/slow-waves, on the real-uV signal)")
    print("=" * 88)
    print(
        "Earlier YASA runs (on Z-scored, and separately on CAR-cancellation-degenerate real-uV) signal "
        "were unreliable -- most windows triggered an outright amplitude-rejection error rather than "
        "running the detector at all, so n_spindles/n_slow_waves were mostly meaningless zeros. Now that "
        "the real-uV signal reflects genuine recorded amplitude (A1/A2 referencing + active-channel-only "
        "averaging), these counts are worth correlating for the first time."
    )
    report_correlations(df, ["n_spindles", "n_slow_waves"], "probability vs YASA event counts")


def report_correlations(df: pd.DataFrame, feature_cols: List[str], label: str) -> None:
    print(f"\n--- POOLED -- {label} ---")
    for col in feature_cols:
        r = spearman_corr(df["probability"].values, df[col].values)
        print(f"  probability vs {col:20s}: Spearman r = {r:+.4f}  (n={len(df)})")

    print(f"\n--- WITHIN-SUBJECT -- {label} ---")
    for col in feature_cols:
        per_subject_r = []
        for _, group in df.groupby("subject_id"):
            if len(group) >= 5 and group[col].std() > 0:
                r = spearman_corr(group["probability"].values, group[col].values)
                if not np.isnan(r):
                    per_subject_r.append(r)
        per_subject_r = np.array(per_subject_r)
        if len(per_subject_r) == 0:
            print(f"  probability vs {col:20s}: no subjects had enough variance to compute this.")
            continue
        print(
            f"  probability vs {col:20s}: mean r = {per_subject_r.mean():+.4f}, "
            f"median r = {np.median(per_subject_r):+.4f} (n_subjects={len(per_subject_r)})"
        )


def report_pairwise(df: pd.DataFrame, cols: List[str], label: str) -> None:
    print(f"\n--- {label} (n_windows={len(df)}) ---")
    for i, c1 in enumerate(cols):
        for c2 in cols[i + 1:]:
            r = spearman_corr(df[c1].values, df[c2].values)
            print(f"  Spearman({c1:22s}, {c2:22s}) = {r:+.4f}")


def report_pairwise_within_subject(df: pd.DataFrame, cols: List[str]) -> None:
    print("\n--- WITHIN-SUBJECT (median across subjects) ---")
    per_subject_rs = {f"{c1}|{c2}": [] for i, c1 in enumerate(cols) for c2 in cols[i + 1:]}
    for _, g in df.groupby("subject_id"):
        if len(g) < 5:
            continue
        for i, c1 in enumerate(cols):
            for c2 in cols[i + 1:]:
                r = spearman_corr(g[c1].values, g[c2].values)
                if not np.isnan(r):
                    per_subject_rs[f"{c1}|{c2}"].append(r)
    for pair, rs in per_subject_rs.items():
        if rs:
            print(f"  {pair:55s}: median_r={np.median(rs):+.4f}  mean_r={np.mean(rs):+.4f}  (n_subjects={len(rs)})")


if __name__ == "__main__":
    main()
